blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/mikeleppane/envx/discussions
    about: Ask questions and discuss ideas with the community
  - name: ğŸ“š Documentation
    url: https://github.com/mikeleppane/envx/wiki
    about: Check out our documentation and guides

